#!/home/izzy/.local/share/pipx/venvs/terminal-rain-lightning/bin/python
import sys
from terminal_rain_lightning import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
