pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// Live Material-You palette, regenerated by matugen every time the
// wallpaper changes. FileView watches the file so colors update in the
// running shell with no restart needed.
Singleton {
    id: root

    property color primary: "#8AB4F8"
    property color textOnPrimary: "#00315C"
    property color primaryContainer: "#0B57D0"
    property color textOnPrimaryContainer: "#D3E3FD"

    property color secondary: "#C2C7CF"
    property color textOnSecondary: "#28303F"

    property color background: "#111318"
    property color textOnBackground: "#E3E2E6"

    property color surface: "#111318"
    property color surfaceContainer: "#1D2024"
    property color surfaceContainerHigh: "#272A2F"
    property color textOnSurface: "#E3E2E6"
    property color textOnSurfaceVariant: "#C4C6D0"

    property color outline: "#8E9099"
    property color error: "#FFB4AB"
    property color success: "#8BD5A0"

    FileView {
        id: colorsFile
        path: Quickshell.env("HOME") + "/.config/quickshell/matushell/data/colors.json"
        watchChanges: true
        printErrors: false
        onLoaded: root.applyColors(text())
        onLoadFailed: error => console.log("Colors: colors.json not found yet — run matugen once")
    }

    function applyColors(jsonText) {
        try {
            const c = JSON.parse(jsonText)
            primary = c.primary ?? primary
            textOnPrimary = c.on_primary ?? textOnPrimary
            primaryContainer = c.primary_container ?? primaryContainer
            textOnPrimaryContainer = c.on_primary_container ?? textOnPrimaryContainer
            secondary = c.secondary ?? secondary
            textOnSecondary = c.on_secondary ?? textOnSecondary
            background = c.background ?? background
            textOnBackground = c.on_background ?? textOnBackground
            surface = c.surface ?? surface
            surfaceContainer = c.surface_container ?? surfaceContainer
            surfaceContainerHigh = c.surface_container_high ?? surfaceContainerHigh
            textOnSurface = c.on_surface ?? textOnSurface
            textOnSurfaceVariant = c.on_surface_variant ?? textOnSurfaceVariant
            outline = c.outline ?? outline
            error = c.error ?? error
        } catch (e) {
            console.log("Colors: failed to parse colors.json:", e)
        }
    }
}
