#!/usr/bin/env python3
"""Generate browser, homepage and Dark Reader themes from one Matugen palette."""
import json, os, re, shutil, subprocess
from pathlib import Path
BASE=Path(__file__).resolve().parent

def write(path,text):
    path.parent.mkdir(parents=True,exist_ok=True)
    tmp=path.with_name(path.name+'.tmp');tmp.write_text(text);tmp.replace(path)

def refresh(notify=True):
    p=json.loads((BASE/'palette.json').read_text())
    if not all(re.fullmatch(r'#[0-9a-fA-F]{6}',v) for v in p.values()):raise ValueError('Invalid palette')
    write(BASE/'home/palette.css', ':root{'+''.join('--'+k+':'+v+';' for k,v in p.items())+'}\n')
    bg,fg,accent,muted,high=p['surface'],p['on_surface'],p['primary'],p['on_surface_variant'],p['surface_container_high']
    settings={}
    for prefix in ['statusbar.normal','statusbar.command','statusbar.private','statusbar.command.private','statusbar.caret','statusbar.caret.selection','statusbar.passthrough','tabs.even','tabs.odd','completion.category','prompts','messages.info','messages.warning','messages.error','keyhint','contextmenu.menu','tooltip']:
        settings['colors.'+prefix+'.bg']=bg;settings['colors.'+prefix+'.fg']=fg
    for prefix in ['tabs.selected.even','tabs.selected.odd','statusbar.insert','completion.item.selected','contextmenu.selected']:
        settings['colors.'+prefix+'.bg']=high;settings['colors.'+prefix+'.fg']=accent
    settings.update({'colors.tabs.bar.bg':bg,'colors.webpage.bg':bg,'colors.completion.even.bg':bg,'colors.completion.odd.bg':bg,'colors.completion.fg':fg,'colors.completion.match.fg':accent,'colors.completion.category.border.top':bg,'colors.completion.category.border.bottom':bg,'colors.completion.item.selected.border.top':high,'colors.completion.item.selected.border.bottom':high,'colors.statusbar.url.fg':muted,'colors.statusbar.url.success.https.fg':accent,'colors.statusbar.url.success.http.fg':accent,'colors.statusbar.url.hover.fg':accent,'colors.statusbar.progress.bg':accent,'colors.hints.bg':accent,'colors.hints.fg':bg,'colors.hints.match.fg':high,'colors.prompts.border':'1px solid '+accent,'colors.downloads.bar.bg':bg})
    write(BASE/'theme.py','# Generated by Matugen\n'+''.join('config.set('+repr(k)+', '+repr(v)+')\n' for k,v in settings.items()))
    options={'mode':1,'brightness':100,'contrast':100,'sepia':0,'darkSchemeBackgroundColor':bg,'darkSchemeTextColor':fg,'selectionColor':accent}
    header='// ==UserScript==\n// @name Izzy Matugen Dark Reader\n// @namespace izzychka\n// @match http://*/*\n// @match https://*/*\n// @run-at document-end\n// @grant none\n// ==/UserScript==\n'
    # Bundle the API locally. No CDN request on each website.
    script=header+'(function(){\n'+(BASE/'darkreader.js').read_text()+'\nconst options='+json.dumps(options)+';\n'+'''
if (window.__izzyDarkReader) return;
let disabled = false;
try { disabled = localStorage.getItem('izzy-darkreader-disabled') === '1'; } catch(e) {}
const apply = () => { if(disabled) DarkReader.disable(); else DarkReader.enable(options); };
window.__izzyDarkReader = {toggle: () => { disabled = !disabled; try {localStorage.setItem('izzy-darkreader-disabled', disabled ? '1' : '0');} catch(e) {} apply(); }};
apply();
})();
'''
    write(BASE.parent/'greasemonkey/izzy-matugen.user.js',script)
    if notify and shutil.which('qutebrowser') and shutil.which('pgrep'):
        running=subprocess.run(['pgrep','-u',str(os.getuid()),'-x','qutebrowser'],stdout=subprocess.DEVNULL).returncode==0
        if running:
            # Send commands to the running default instance without reloading web pages.
            quoted='"'+str(BASE/'theme.py').replace('\\','\\\\').replace('"','\\"')+'"'
            subprocess.run(['qutebrowser', ':config-source '+quoted, ':greasemonkey-reload --quiet'],timeout=15,check=False)
if __name__=='__main__':refresh()
